name: KatalonDockerCI
on:
  push:
    branches:
      - HELPDESK-1070
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
        KS_VERSION: 8.3.0
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: registry.hub.docker.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to dockerhub
      run: |
        echo Username: ${{ secrets.DOCKER_USERNAME }} Password: ${{ secrets.DOCKER_PASSWORD }} docker.io
